# Remove the version line if it exists
version: '3.8'

volumes:
  mariaimmo:
  shared_files:
  converted_files:

services:

  immobase:
    container_name: ${DB_CONTAINER_NAME}
    image: mariadb:latest
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mariaimmo:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: ${TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

  immophp:
    container_name: phpCOSY
    build:
      context: ./php
      dockerfile: Dockerfile
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '${PHP_PORT}:9000'
    environment:
      DEBUG: '1'
      PHP_DISPLAY_ERRORS: '1'
      PHP_POST_MAX_SIZE: '100M'
      PHP_UPLOAD_MAX_FILESIZE: '100M'
      TZ: ${TIMEZONE}
    volumes:
      - ./app:/var/www/html
      - ./MP3_MUSICS:/var/www/html/MP3_MUSICS
    user: www-data
    depends_on:
      - immobase
    networks:
      - app-network

  immonode:
    tty: true
    container_name: ${NODE_CONTAINER_NAME}
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    restart: always
    environment:
      TZ: ${TIMEZONE}
    depends_on:
      - immophp

  immonginx:
    container_name: ${NGINX_CONTAINER_NAME}
    image: nginx:stable-alpine
#    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
    restart: always
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx/
    depends_on:
      - immophp
      - immobase
      - immonode
    networks:
      - app-network

  immopython:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python:/usr/src/app
      - ./MP3_MUSICS:/var/www/html/MP3_MUSICS
    ports:
      - "5000:5000"
    environment:
      TZ: ${TIMEZONE}
      DB_HOST: immobase
      DB_PORT: ${DB_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      API_HOST: host.docker.internal  # This allows connecting to the host machine
      API_PORT: 81
    user: www-data
    depends_on:
      - immophp
      - immonginx
      - immobase
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
